### ISSUE TITLE
Display various component versions somewhere?

### ISSUE THREAD

**Issue by jcwren** [brocaar/chirpstack-application-server#432] opened 2020-02-28 16:07 UTC
### Is this a bug or a feature request?
Feature

### What version are your using?
3.9.0

Perhaps I'm just overlooking it, but there doesn't seem to be anywhere in the web UI that displays the version of the various components (network server, app server, geo location, etc). Perhaps an 'About' box under the drop-down for 'Logout' and 'Change password'?

The only way I know to check it right now is to dig through the log file, and that's a bit more painful when running under a docker image.

Bonus points if it checks the GitHub releases and puts a '!' next to the components that are not the most current :)

**Comment by brocaar** [comment] 2020-04-03 14:13
Duplicate of #316.

**Closed by brocaar** 2020-04-03 14:13 UTC
